### ISSUE TITLE
升级 elasticsearch 到 1.4.3

### ISSUE THREAD

**Issue by sorrycc** [afc163/elasticsearch-package#1]
https://github.com/spmjs/spm/issues/1221
http://bobao.360.cn/news/detail/1273.html

**Comment by afc163** [comment]
1.4.3 published. https://www.npmjs.com/package/elasticsearch-package

**Comment by LeoYuan** [comment]
升级到1.4.3后，本机运行直接报类找不到~
![image](https://cloud.githubusercontent.com/assets/1195765/7060985/884728a8-debd-11e4-8600-db25d52465a7.png)

但有点奇怪的是，我刚刚还发布了一把，在编译机上会走`tnpm install`后推送到正式机器，运行正常~
![image](https://cloud.githubusercontent.com/assets/1195765/7060973/36d16902-debd-11e4-9b4a-9b20ccf31675.png)

**Comment by afc163** [comment]
https://github.com/Homebrew/homebrew/issues/29910

是否是 Java 7 环境？

**Comment by afc163** [comment]
@LeoYuan 的确有问题，我重新发了个 1.5 的版本，应该修复了，试试这个。

**Comment by LeoYuan** [comment]
Problem resolved~
